# wget -qO- https://download.processing.org/processing-3.5.4-linux64.tgz | tar -xz
# $PATH=$PATH:./processing-3.5.4

# DEPLOY_F=true
# if [[ $DEPLOY_F = true ]]; then echo "hiii"; else echo "no"; fi

language: node_js

node_js:
  - 12

notifications:
  email: false

branches:
  only:
    - master

script:
  - echo "test if deploy"
  - LATEST_COMMIT=$(git log -1 --format=format:%H --full-diff .)
  - LATEST_BOT_COMMIT=$(git log -1 --format=format:%H --full-diff ./algotypes_bot)
  - LATEST_P5_COMMIT=$(git log -1 --format=format:%H --full-diff ./0x*/p5*)
  - |
    if [[ $LATEST_COMMIT == $LATEST_BOT_COMMIT ]]; then
      echo "Deploy Heroku";
      DEPLOY_BOT=true;
    fi
  - |
    if [[ $LATEST_COMMIT == $LATEST_P5_COMMIT ]]; then
      echo "Deploy P5";
      DEPLOY_P5=true;
    fi

before_deploy:
  - |
    if [[ $DEPLOY_BOT = true ]]; then
      echo "Deploy Bots";
      cd algotypes_bot;
    fi
  - |
    if [[ $DEPLOY_P5 = true ]]; then
      echo "Deploy P5 cards";
      wget -qO- https://download.processing.org/processing-3.5.4-linux64.tgz | tar -xz;
      PATH=$PATH:./processing-3.5.4;
      mkdir out;
      xvfb-run processing-java --sketch=$PWD/0x00-PRNG/p5_0x00_PRNG --run SCREEN;
      tar -czf cards.tar.gz out;
      git config --local user.name "$USER_NAME";
      git config --local user.email "$USER_EMAIL";
      git tag "$TRAVIS_BRANCH-$(git log --format=%h -1)";
    fi

deploy:
  - provider: heroku
    api_key: $HEROKU_KEY
    app: algotypes-bot
    on:
      condition: $DEPLOY_BOT = true
  - provider: releases
    token: $GHTOKEN
    file: "cards.tar.gz"
    release_notes: "$TRAVIS_BRANCH: $TRAVIS_COMMIT_MESSAGE"
    target_commitish: $TRAVIS_COMMIT
    skip_cleanup: true
    on:
      all_branches: true
      condition: $DEPLOY_P5 = true
