language: node_js

node_js:
  - 12

notifications:
  email: false

branches:
  only:
    - master

script:
  - echo "test if deploy"
  - ./.travis.check.sh

before_deploy:
  - cd algotypes_bot

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: algotypes-bot
