language: node_js

node_js:
  - 12

notifications:
  email: false

branches:
  only:
    - master

script:
  - echo "test if deploy"
  - if [[ `./.travis.check.sh` ]]; then >&2 echo "Don't Deploy"; exit 1; fi

before_deploy:
  - cd algotypes_bot

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: algotypes-bot
