language: node_js

node_js:
  - 12

notifications:
  email: false

branches:
  only:
    - master

script:
  - echo "test if deploy"
  - LATEST_COMMIT=$(git log -1 --format=format:%H --full-diff .)
  - LATEST_COMMIT_IN_PATH=$(git log -1 --format=format:%H --full-diff ./algotypes_bot)
  - if [[ $LATEST_COMMIT != $LATEST_COMMIT_IN_PATH ]]; then echo "Don't Deploy"; exit 0; else echo "Deploy"; fi

before_deploy:
  - cd algotypes_bot

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: algotypes-bot
